# Generated by Django 4.2 on 2023-04-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_profile_avatar_alter_question_tag_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlikes',
            name='question',
        ),
        migrations.AddField(
            model_name='profile',
            name='answers_likes',
            field=models.ManyToManyField(blank=True, to='askme.answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_likes',
            field=models.ManyToManyField(blank=True, to='askme.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='human_format_rating',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
        migrations.DeleteModel(
            name='QuestionLikes',
        ),
    ]
