# Generated by Django 4.2 on 2023-04-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_remove_questionlikes_question_profile_answers_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='questions_likes',
        ),
        migrations.AlterField(
            model_name='question',
            name='human_format_rating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('l', 'Like'), ('d', 'Dislike')], max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('l', 'Like'), ('d', 'Dislike')], max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.answer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.profile')),
            ],
        ),
    ]
