# Generated by Django 4.2 on 2023-04-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_remove_profile_answers_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='user_id',
            new_name='user',
        ),
    ]
