# Generated by Django 4.2 on 2023-04-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_rename_user_id_answerlike_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('user', 'question')},
        ),
    ]
