# Generated by Django 4.2 on 2023-05-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0010_answer_human_format_rating_answer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
