# Generated by Django 4.2 on 2023-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0016_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='human_format_rating',
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_flag',
            field=models.BooleanField(default=False),
        ),
    ]
